feat(Chat): Convert text into emojis on chatbar when settings for it is enabled
Satellite-im/UplinkWeb pull request #536
Opened 2024-09-10 19:54 UTC by lgmarchi

### What this PR does 📖
#### 1. Convert text into emojis on chatbar when settings for it is enabled, just for smileys and emotions

https://github.com/user-attachments/assets/b6da2b81-30f8-4b9b-bea0-29227c40027e

### Which issue(s) this PR fixes 🔨

- Resolve #528 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-09-10 22:59 UTC, luisecm commented
Working good for me. Updated the snapshots on testing repository and rerunning CI automated tests. PR approved from my side

2024-09-10 22:59 UTC, luisecm approved these changes

2024-09-11 13:43 UTC, stavares843 commented on src/lib/components/messaging/emoji/category/activities.ts
> +        name: "game die",
```suggestion
        name: "game dice",
```

2024-09-11 13:49 UTC, stavares843 requested changes
when going npm run build appears this warning

<img width="1500" alt="Captura de ecrã 2024-09-11, às 14 48 08" src="https://github.com/user-attachments/assets/439445ab-0059-4812-82b4-963542491234">


it does not happen on dev

2024-09-11 13:53 UTC, stavares843 commented on src/lib/components/messaging/emoji/category/foodAndDrink.ts
> +        glyph: "🍋‍🟩",
is this on purpose? the green cube

2024-09-11 17:01 UTC, InfamousVague approved these changes

2024-09-11 17:10 UTC, merged