feat(chat): Group calling
Satellite-im/UplinkWeb pull request #565
Opened 2024-09-17 17:12 UTC by Flemmli97

### What this PR does 📖

- Implements group calling:
  - Adds in a mesh architecture that connects everyone with each other
  - If someone joins the mesh that user will be forwarded to all the others and they will try to connect to the user too. If this request comes from someone in the same call the call will be automatically accepted
- Also adds isTalking handling

### Which issue(s) this PR fixes 🔨

- Resolve #393

### Notes
- UI rework needs to be still done
- Video is not toggable from the other users end (the caller can toggle). But idk if this is due to my setup where i test it on the same computer or not.
- Ending the call does not turn off camera. prob same cause as above
(Note 2 and 3 also happens in dev this way though)

2024-09-18 14:46 UTC, Flemmli97 commented
> Something I noticed while testing (I can make this into a new ticket if we just wanna get this merged in)
> 
> If User A calls a group with User B and User C and only User B answers the call, it will still look like UserC is in the call with them even though he is not
> 
> Like I said lemme know if this would be better handled in a new ticket and I will be happy to create one!
> 
>  Screen_Recording_2024-09-17_at_4.52.49_PM.mov

changed that now

2024-09-18 17:03 UTC, Flemmli97 commented
> Looks better but just found one thing that happens now after the fix
> 
> When UserA/B are in the call and UserC deny's it, once UserC hits deny the ringtone will re-appear and the user will need to deny it again
> 
>  Screen.Recording.2024-09-18.at.11.50.10.AM.mov

are there any other problems? does the main thing all work?

2024-09-18 17:31 UTC, lgmarchi approved these changes

2024-09-18 20:58 UTC, Flemmli97 commented
> > > Looks better but just found one thing that happens now after the fix
> > > When UserA/B are in the call and UserC deny's it, once UserC hits deny the ringtone will re-appear and the user will need to deny it again
> > > Screen.Recording.2024-09-18.at.11.50.10.AM.mov
> > 
> > 
> > are there any other problems? does the main thing all work?
> 
> Seems for the most part general calling works. If we want once the conflicts are fixed I will approve and create tickets for any issues

i will fix the issue above in this pr still

2024-09-19 14:57 UTC, stavares843 commented on src/lib/media/Voice.ts
> +                // Call after successfuly connect. But dont wait for it
```suggestion
                // Call after successfully connect. But dont wait for it
```

2024-09-19 14:57 UTC, stavares843 commented on src/lib/components/calling/CallScreen.svelte
> +        // }
do we need this?

2024-09-19 14:57 UTC, stavares843 commented on src/lib/media/Voice.ts
> +    JoinedCall = "JOINED_CALL",
should this be JOINING? to be joining/leaving

2024-09-19 14:57 UTC, stavares843 commented on src/lib/media/Voice.ts
> +        // TODO: decide which video to play?
maybe we could by default show the video of who started the call

2024-09-19 14:57 UTC, stavares843 commented on src/lib/media/Voice.ts
> +    // }
do we need this?

2024-09-19 14:57 UTC, stavares843 commented on src/lib/media/VoiceO.ts
> +import { CallDirection } from "$lib/enums"
do we need this file? src/lib/media/VoiceO.ts or was this for testing?


if so, can we update the naming?

2024-09-19 17:14 UTC, InfamousVague approved these changes

2024-09-19 17:14 UTC, InfamousVague commented on src/routes/+layout.svelte
> +        <!-- <VideoPreview /> This needs a rework as atm it only supports one to one calling. Maybe add ability to select source? -->
Ideally this should show the video of whoever is talking at the time, I know this is more involved so no worries about this in this PR but let's get a ticket opened up so we don't forget about it

2024-09-19 18:13 UTC, stavares843 reviewed
@phillsatellite and i were testing the PR

feedback

Phil's Call Issue (Unanswered Modal):
Scenario: Phil started a call, and one of the users saw the call modal appear but was unable to answer it.

User Count Discrepancy:
Scenario: During a call, only one user had joined, but the system indicated that three users were present.

Unknown User on Call Modal:
Scenario: When Phil called Sara, the call modal displayed "Unknown User" instead of Sara's name.

No Call Modal Appearing:
Scenario: Phil called Sara, but no call modal appeared on her side.

Ringtone Without Modal:
Scenario: Phil called Sara, and while she heard the ringtone, the call modal did not appear.

Call Not Starting or Missed Call Notifications:
Scenario: Sara attempted to initiate an audio or video call, but it didn’t start. Phil then called Sara, but no call appeared for her, nor did missed call notifications show up in the chat. After refreshing the app, the issue was resolved.

Phil's Call Issue (No Calls Initiated):
Scenario: Phil attempted to call Sara, but the call was not initiated.

2024-09-20 12:20 UTC, Flemmli97 commented on src/lib/media/Voice.ts
> +    // }
its from dev. but unused atm

2024-09-20 13:59 UTC, Flemmli97 commented
can you post the logs for the first problem?
and for the rest have you tried the up to date code? (i also pushed some otherstuff just now)

2024-09-20 14:51 UTC, stavares843 commented
we don't have logs for the first issue - we can try to reproduce and get logs

but yes we had the branch updated on our side, new account, clean builds and everything

2024-09-20 14:52 UTC, stavares843 commented on src/lib/media/Voice.ts
> +        const maxRetries = 5 // TODO: Failing to connect after 2 attemps (or just throwing errors twitce for the local peer?) breaks ALL connections...
```suggestion
        const maxRetries = 5 // TODO: Failing to connect after 2 attempts (or just throwing errors twice for the local peer?) breaks ALL connections...
```
```suggestion
        const maxRetries = 5 // TODO: Failing to connect after 2 attemps (or just throwing errors twitce for the local peer?) breaks ALL connections...
```

2024-09-20 14:52 UTC, stavares843 commented
we will try again with your latest commit to see if they still happen

2024-09-20 15:34 UTC, stavares843 commented
so @phillsatellite and i retested with latest commit

Phil called Sara. When Sara answered, the call didn't appear on her side, but Phil saw that Sara was on the call. 

Later, Sara called Phil, and though Phil successfully joined the call, Sara couldn't see Phil on the line, while Phil saw her as being connected.



Phil side

![image](https://github.com/user-attachments/assets/58f79def-a877-40ee-a276-91bae95867a1)


Sara side

![image](https://github.com/user-attachments/assets/560da888-3eb5-40a4-b377-548eaf262270)

2024-09-25 16:30 UTC, luisecm commented
@Flemmli97 @stavares843 Looks like the build android job is failing on this branch - https://github.com/Satellite-im/UplinkWeb/actions/runs/11036050320/job/30653555494?pr=565

2024-09-26 03:07 UTC, InfamousVague approved these changes

2024-09-26 15:44 UTC, phillsatellite commented
Noticed some things while testing the latest 

When the call came in for User B & C it appeared as though it was coming from an unknown user 

All the users joined the call but on User A & C side it says only 2 users are in the call. For user B it showed only themselves in the call 

When User A hangs up it also hung up the call for User B. User C still remains in the call 


https://github.com/user-attachments/assets/61b667db-4445-4497-8a6c-4c9e91c0cc75

<img width="856" alt="Screenshot 2024-09-26 at 11 40 02 AM" src="https://github.com/user-attachments/assets/e8085d8d-fae7-4977-9ec5-c5149d9536df">

2024-09-27 14:40 UTC, Flemmli97 commented
what happens if you wait a bit longer? sometimes i had the problem of needing to wait quite a few seconds. even for 1 to 1 call

2024-09-30 12:35 UTC, Flemmli97 commented
> Noticed some things while testing the latest
> 
> When the call came in for User B & C it appeared as though it was coming from an unknown user
> 
> All the users joined the call but on User A & C side it says only 2 users are in the call. For user B it showed only themselves in the call
> 
> When User A hangs up it also hung up the call for User B. User C still remains in the call
> 
>  Screen.Recording.2024-09-26.at.11.37.33.AM.mov 
> 
> <img alt="Screenshot 2024-09-26 at 11 40 02 AM" width="856" src="https://private-user-images.githubusercontent.com/93608357/371219870-e8085d8d-fae7-4977-9ec5-c5149d9536df.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc2OTcyNzcsIm5iZiI6MTcyNzY5Njk3NywicGF0aCI6Ii85MzYwODM1Ny8zNzEyMTk4NzAtZTgwODVkOGQtZmFlNy00OTc3LTllYzUtYzUxNDlkOTUzNmRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTMwVDExNDkzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY2ODhiMjNkZjVlN2EwZTUwMjlhNGU4OWNmODZmZjA3ZWI5OTZhZGQ2Njc4YTI4MjY4ZjAwZGJlNzdhZTQzM2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.d2aZ3_OKDjcjYGNaAxgqhF7qTtfcGbUcGyAgv-_PiPY">

i fixed various stuff. but as for users not showing up:
it has to do with multipass failing to find the identity at the start.
i can implement a retry system there but since that is not directly involved with calling would it be better to do it in a new PR?

2024-09-30 15:21 UTC, stavares843 commented
we will test again

2024-10-01 11:02 UTC, Flemmli97 commented
check with #653 to see if its still a problem with users not showing up during call

2024-10-01 11:08 UTC, Flemmli97 commented
also one more issue that might be resolved is #463. at least using this branch i dont have that problem

2024-10-01 15:20 UTC, phillsatellite commented
> also one more issue that might be resolved is #463. at least using this branch i dont have that problem

@Flemmli97 both of these issues do not happen in #653 💥

2024-10-01 19:48 UTC, stavares843 requested changes
phil called me and i called phil both group and 1:1 and always say 1 user on call


![image](https://github.com/user-attachments/assets/226f1e0a-8da2-4195-953d-6459378e01e6)

2024-10-02 15:35 UTC, Flemmli97 commented
hmm can you post the whole console log?

2024-10-02 17:00 UTC, phillsatellite commented
<img width="847" alt="Screenshot 2024-10-02 at 1 00 40 PM" src="https://github.com/user-attachments/assets/fa8d7c65-c54a-40c0-9fa9-36ee1f60e1ae">

2024-10-02 17:06 UTC, Flemmli97 commented
can you try add this line in Voice.ts `console.log("own did: ", get(Store.state.user).key)` in line 452? before the connect call. and then see what it prints. this is on the side of the caller.
cause from the pic you send it seems its sending an undefined did over

2024-10-02 17:06 UTC, Flemmli97 commented
> can you try add this line in Voice.ts `console.log("own did: ", get(Store.state.user).key)` in line 452? before the connect call. and then see what it prints. this is on the side of the caller. cause from the pic you send it seems its sending an undefined did over
maybe an account is corrupt?

2024-10-02 17:20 UTC, phillsatellite commented
> can you try add this line in Voice.ts `console.log("own did: ", get(Store.state.user).key)` in line 452? before the connect call. and then see what it prints. this is on the side of the caller. cause from the pic you send it seems its sending an undefined did over maybe an account is corrupt?

Will give it a shot. And shouldnt be a corrupt account these were all brand new

2024-10-02 21:46 UTC, phillsatellite commented
@Flemmli97 Sara and I retested and it is now showing the correct amount of users in the call. There just seems to be another issue that is appearing now. 

When you are in a group call there is maybe 5 seconds in the beginning of the call when the sound works and after that 5 seconds there is no sound even if you try to mute/unmute or deafen/undeafen users cannot hear each other at all. On dev branch audio on calls are fine 

<img width="854" alt="Screenshot 2024-10-02 at 5 42 15 PM" src="https://github.com/user-attachments/assets/ae5f8169-7451-4534-b7a0-c37f2c0178aa">

2024-10-04 22:26 UTC, stavares843 approved these changes

2024-10-04 22:27 UTC, merged