feat(Call): Add username when user does not have video
Satellite-im/UplinkWeb pull request #745
Opened 2024-10-21 20:40 UTC by lgmarchi

### What this PR does 📖

- Show username underneath user who is not using video feed
<img width="298" alt="image" src="https://github.com/user-attachments/assets/6827c458-a768-4bc5-a8fe-61eab6ffb513">

### Which issue(s) this PR fixes 🔨

- Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-10-21 22:58 UTC, stavares843 commented on src/lib/components/calling/Participant.svelte
> +            text-align: center; /* Alinha o texto no centro */
do we need the comment?

2024-10-21 22:58 UTC, stavares843 commented on src/lib/components/calling/Participant.svelte
> +            display: flex; /* Alinha a imagem e o nome lado a lado */
do we need the comment?

2024-10-21 23:19 UTC, lgmarchi commented on src/lib/components/calling/Participant.svelte
> +            display: flex; /* Alinha a imagem e o nome lado a lado */
We don't, removed.

2024-10-21 23:46 UTC, lgmarchi commented on src/lib/components/calling/Participant.svelte
> +            text-align: center; /* Alinha o texto no centro */
We don't, removed.

2024-10-22 16:55 UTC, phillsatellite approved these changes

2024-10-22 16:58 UTC, luisecm commented
@lgmarchi hey, I have checked about the test failing on this pr and its related to a minor css change on the enable/disable video button from call screen when enabling the camera. I  don't see anything wrong with the videocalls functionality in your branch so I went ahead and added a pr on the testing repo to update the css value expected by the test when doing this action in here - https://github.com/Satellite-im/automated-tests-web/pull/186

2024-10-22 17:24 UTC, InfamousVague requested changes

2024-10-22 17:24 UTC, InfamousVague commented on src/lib/components/calling/Participant.svelte
> +            font-size: 14px;
lets use the text component and use the size={Size.Smaller}  (or smallest) for this so that it matches up

2024-10-22 17:24 UTC, InfamousVague commented on src/lib/components/calling/Participant.svelte
> +            <div class="user-name">{participant.name}</div>
`<Text singleLine size={Size.Smaller}>{participant.name}</Text>`

2024-10-22 18:20 UTC, InfamousVague approved these changes

2024-10-22 18:21 UTC, merged