fix(groups): group user list
Satellite-im/UplinkWeb pull request #810
Opened 2024-10-31 16:13 UTC by Flemmli97

### What this PR does 📖

- Fix group participants inconsistency:
  - It was possible to "remove" (only visually) users by clicking on the user list instead of the buttons on top

2024-11-01 16:53 UTC, phillsatellite commented
Hey Kevin! I think this bug fits the scope of this pr but we can handle it in another ticket if need be. So while testing it seems removing a user on the top bar will work fine but if you scroll through the list and remove them from there it doesn't actually remove them it will just reselect them 

https://github.com/user-attachments/assets/bb30b325-9e8c-424a-9c18-613d90f3890a

2024-11-04 12:34 UTC, Flemmli97 commented
> Hey Kevin! I think this bug fits the scope of this pr but we can handle it in another ticket if need be. So while testing it seems removing a user on the top bar will work fine but if you scroll through the list and remove them from there it doesn't actually remove them it will just reselect them
> 
>  Screen.Recording.2024-11-01.at.12.51.17.PM.mov

yes thats intended. the list shows ALL friends of yours. if they are selected they are in the group

2024-11-04 18:00 UTC, phillsatellite commented
> > Hey Kevin! I think this bug fits the scope of this pr but we can handle it in another ticket if need be. So while testing it seems removing a user on the top bar will work fine but if you scroll through the list and remove them from there it doesn't actually remove them it will just reselect them
> > Screen.Recording.2024-11-01.at.12.51.17.PM.mov
> 
> yes thats intended. the list shows ALL friends of yours. if they are selected they are in the group

Yeah I see the list shows all your friends but check out the video I added again. If you try to unselect someone from the list it just re adds them quickly  same with trying to select someone from the list when you click them it'll select them for a moment and then unselect them

2024-11-04 18:03 UTC, lgmarchi requested changes

2024-11-04 18:03 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
> +            Store.addToastNotification(new ToastMessage("", `You can not remove the group creator`, 2))
Add this message on our en.json file

2024-11-04 18:03 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
> +            Store.addToastNotification(new ToastMessage("", `A group can not exist with one person`, 2))
Add this message on our en.json file

2024-11-04 18:03 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
> +            Store.addToastNotification(new ToastMessage("", `A group can not exist with one person`, 2))
Add this message on our en.json file

2024-11-04 18:03 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
>              Store.addToastNotification(new ToastMessage("", `You can not remove the group creator`, 2))
Add this message on our en.json file

2024-11-05 16:27 UTC, lgmarchi commented
@Flemmli97 It just work to add a user to the group, but it does not work to remove user from a group. 

See the video video below to understand: 


https://github.com/user-attachments/assets/82c7f14d-3a7b-49a3-90c8-b1f4c92edc57

2024-11-05 16:35 UTC, Flemmli97 commented
> @Flemmli97 It just work to add a user to the group, but it does not work to remove user from a group.
> 
> See the video video below to understand:
> 
>  Screen.Recording.2024-11-05.at.13.26.26.mov

hmm its working on my end

https://github.com/user-attachments/assets/83657f91-6dd4-438f-85af-120bcfea2643

can you post the logs?

2024-11-05 16:48 UTC, lgmarchi requested changes
There are some changes necessary yet.

2024-11-05 16:48 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
>      function remove_member(user: User) {
We use cammelCase for the name of the functions and variables.

So the correct is removeMembers.

2024-11-05 16:48 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
>      function update_members(user: User) {
We use cammelCase for the name of the functions and variables.

So the correct is updateMembers.

2024-11-05 16:48 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
>          let group_members = [...members]
groupMembers.

2024-11-05 16:48 UTC, lgmarchi commented on src/lib/components/group/ViewMembers.svelte
>      function remove_member(user: User) {
With new code in update_members, we can remove this function and use just one.

2024-11-05 16:50 UTC, lgmarchi commented
> > @Flemmli97 It just work to add a user to the group, but it does not work to remove user from a group.
> > See the video video below to understand:
> > Screen.Recording.2024-11-05.at.13.26.26.mov
> 
> hmm its working on my end
> 
>  2024-11-05.17-34-02.mp4 
> can you post the logs?

Never mind, probably was a cache problem here. Now it is working good.

2024-11-05 17:18 UTC, lgmarchi approved these changes
Code looks good and it is working as expected as well.


https://github.com/user-attachments/assets/dd8ed1fa-02ba-4a55-849e-4a79557aeab4

2024-11-06 00:02 UTC, stavares843 requested changes
https://github.com/user-attachments/assets/74498dba-2234-4b2c-9b11-a063a14b6706

does not work if you are not the group creator

flow
- someone else creates the group
- try to do the above flow
- it removes and after some seconds adds right away

only works if you are the group creator

2024-11-06 09:55 UTC, Flemmli97 commented
> Gravacao.do.ecra.2024-11-05.as.23.57.38.mov 
> does not work if you are not the group creator
> 
> flow
> 
> * someone else creates the group
> * try to do the above flow
> * it removes and after some seconds adds right away
> 
> only works if you are the group creator

yes. permission got redone with new wasm update

2024-11-06 15:49 UTC, Flemmli97 commented
i would suggest we keep this pr as is as ill address the permission thing in another pr

2024-11-06 20:03 UTC, stavares843 commented
added blocked label, being discussed with flem

2024-11-06 20:24 UTC, stavares843 commented
after discussing with flem, merging as is and will fix the non admin stuff in another PR

2024-11-06 20:25 UTC, stavares843 approved these changes

2024-11-06 20:25 UTC, merged