fix(payments): update ui and verbiage for payment bubbles
Satellite-im/UplinkWeb pull request #813
Opened 2024-11-04 14:11 UTC by Jekrimo

### What this PR does 📖

-update ui and verbiage for payment bubbles

### Which issue(s) this PR fixes 🔨

- Resolve #663 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-11-04 20:47 UTC, InfamousVague approved these changes

2024-11-04 22:20 UTC, stavares843 requested changes
@phillsatellite and i were testing and we have the following feedback

browser: chrome


| Issue Description | Suggested Fix | Screenshot/Video |
|-------------------|---------------|------------------|
| When a user sends a request, it says "Send request," but it should say "Request has been sent." The current wording also appears like a clickable button. | Update the text to "Request has been sent" and ensure it does not resemble a clickable button. | ![Screenshot 1](https://cdn.discordapp.com/attachments/908772949409005679/1303105804597198940/Screenshot_2024-11-04_at_4.17.09_PM.png?ex=672a8b5a&is=672939da&hm=ea56c8e325a7ca67845d820a06a3529e7507510f01aaa81b88d37d3cc3264038&) |
| The request notification is missing information about the coin and amount. | Include details of the coin and amount in the request notification. First screenshot is from the PR, second screenshot is from dev. | ![Screenshot 2](https://cdn.discordapp.com/attachments/908772949409005679/1303105812008271952/Captura_de_ecra_2024-11-04_as_21.17.12.png?ex=672a8b5c&is=672939dc&hm=f5c9c90c967af8465c1facae72a0a43b87b3e5f4fdd53c5f134e6aa968a0f2bc&) <br> ![Screenshot 2 - dev](https://cdn.discordapp.com/attachments/908772949409005679/1303113640420835429/Captura_de_ecra_2024-11-04_as_21.48.18.png?ex=672a92a6&is=67294126&hm=7a79f4055debfaff78cf9791b5bcd48686c8d75a91cd1cdaa17a329ac97c80e6&) |
| When User A sends a request to User B, and User B cancels it, `/reject` appears in the sidebar preview. | Replace `/reject` in the sidebar with a clearer status message, such as "Request Rejected." | ![Screenshot 3](https://cdn.discordapp.com/attachments/908772949409005679/1303106531746779207/Captura_de_ecra_2024-11-04_as_21.20.04.png?ex=672a8c07&is=67293a87&hm=315b63100d47f8d6c8175d04c3169c840b04c77c442823786e5292c652b1d1c7&) |
| When User A sends a request to User B, and User A cancels it, "Payment canceled" appears, which is misleading. There’s also an additional message saying "You canceled." | Change "Payment canceled" to a clearer status like "Request canceled by you." Consider consolidating this message to update the original notification instead of adding a new message. | ![Screenshot 4](https://cdn.discordapp.com/attachments/908772949409005679/1303107534089097277/Captura_de_ecra_2024-11-04_as_21.24.01.png?ex=672a8cf6&is=67293b76&hm=2b01790f6b17d9efd92c9705358099f44165d4f3a84867d84f991988496c7438&) |
| User A sends a request to User B, and User B cancels it, resulting in an empty message for User A. | Ensure a descriptive message is shown to User A when User B cancels the request, e.g., "User B canceled your request." | ![Screenshot 5](https://cdn.discordapp.com/attachments/908772949409005679/1303108577350647808/Captura_de_ecra_2024-11-04_as_21.28.11.png?ex=672a8def&is=67293c6f&hm=6eacba20a52a43f8c57b4da329d38a45c04824bf08e53567f215b3ee0039caf6&) |
| Sometimes clicking on send coin returns error on console but no error on the UI. | Display a user-friendly error message on the UI when a console error occurs, or resolve the underlying error if possible. | ![Screenshot 6](https://cdn.discordapp.com/attachments/908772949409005679/1303109562944979025/Captura_de_ecra_2024-11-04_as_21.32.06.png?ex=672a8eda&is=67293d5a&hm=b26901d6bc70c7743dacf85605d4c37fd66bf79b7695f60ad0282fd84180abc9&) |
| If you get a request, click it and then exit without sending, and then try to click send coin again, it will not do anything. | Ensure that exiting without sending does not "lock" the Send Coin button. Reset the button state when the request window is closed without completion. | N/A |
| Sometimes a user is not able to send any requests for ETH or BTC; the request button just doesn't change to clickable. | Investigate and fix the issue preventing the request button from becoming clickable, ensuring it updates appropriately based on user action. | N/A |
| When clicking on pay for BTC, it opened the Xverse app, but for ETH, it just gives an error in the console. | Make the pay functionality consistent across currencies, so that clicking pay for ETH initiates the appropriate action without console errors. | ![Screenshot](https://cdn.discordapp.com/attachments/908772949409005679/1303114986675114105/Captura_de_ecra_2024-11-04_as_21.53.40.png?ex=672a93e7&is=67294267&hm=a1703f53e128bade978190df14adf44174e40e0ec6b544b3227f22b07a1a44c3&) |

2024-11-05 18:01 UTC, lgmarchi requested changes
I requested some changes to let code cleaner

2024-11-05 18:01 UTC, lgmarchi commented on src/lib/lang/en.json
> +        "decline_payment": "Decline Payment",
Jeff, we don't use snake_case on Uplink, we use cammelCase. Could you change please?

2024-11-05 18:01 UTC, lgmarchi commented on src/lib/utils/Wallet.ts
> +    torejectString(id: string) {
toRejectString would be better. With R.

2024-11-05 18:01 UTC, lgmarchi commented on src/lib/utils/Wallet.ts
> +        } catch {}
Let's add a log here, just to let us know that JSON.parse failed.

2024-11-05 18:01 UTC, lgmarchi commented on src/lib/utils/Wallet.ts
> +        } catch {}
Same thing here about error log. Or at least warning log if it not so bad.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +    function build_context_items(message: MessageType, file?: Attachment) {
Let change to cammelCase my friend. buildContextItems.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +        let rejectTranser = transfer.torejectString(message.id)
Transer is wrong, change to Transfer.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                        console.log(`MessageId ${message.id} is already in the rejected payments list`)
Let's use our Logger here my friend.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                        console.log(`MessageId ${message.id} is already in the rejected payments list`)
Use our Logger here.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +        const idMatch = messageLine.match(/^\/reject\s([a-f0-9-]{36})$/)
We can put this regex in a const variable in utils?

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                                                        {#if line.startsWith("/reject")}
My friend, we use a lot of "/reject" in our code, and "/request" as well. What do you think to put those values in const variables?

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                                                                    <Text hook="text-chat-message" markdown={"Payment Rejected"} appearance={group.details.remote ? Appearance.Default : Appearance.Alt
Those strings "Payment Rejected" and "You canceled", can we put them on variables?

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                                                                    <Button hook="text-chat-message" text={$_("payments.decline_payment")} appearance={Appearance.Error} on:click={async () => sendPaym
reject here is magic string, let put in a variable as well.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                                                                    <Button hook="text-chat-message" text={$_("payments.cancel_request")} appearance={Appearance.Error} on:click={async () => sendPayme
Same about "reject" string here.

2024-11-05 18:01 UTC, lgmarchi commented on src/routes/chat/+page.svelte
> +                                                                    <Button hook="text-chat-message" text={$_("payments.canceled_request")} appearance={Appearance.Error} on:click={async () => sendPay
Same about "reject" string here.

2024-11-07 22:38 UTC, phillsatellite approved these changes

2024-11-08 19:03 UTC, stavares843 approved these changes

2024-11-08 19:06 UTC, stavares843 commented
we shall address the rest of the feedback in separate PR's

2024-11-11 12:47 UTC, lgmarchi approved these changes

2024-11-11 12:51 UTC, merged