fix(Call): Fix flash talk indicator
Satellite-im/UplinkWeb pull request #825
Opened 2024-11-08 17:03 UTC by lgmarchi

### What this PR does 📖

This pull request introduces several enhancements and bug fixes to the `src/lib/media/Voice.ts` file, including the addition of voice activity detection, improvements to relay server testing, and updates to audio handling. Additionally, there are updates to the `package.json` and `vite.config.js` files to support these changes.

### Voice Activity Detection:
* Added the `voice-activity-detection` library to detect when a user is speaking and update the media state accordingly. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4L8-R14) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R132-L136)

### Relay Server Testing:
* Introduced a method to test the connectivity of relay servers and update the list of available relays dynamically. [[1]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R30-R43) [[2]](diffhunk://#diff-a75896c18790a15b7e0ae422d555a80c3e09067296e47a5dcc6891ab3385dfb4R639-R697)

### Audio Handling:
* Simplified audio constraints by removing specific audio settings such as echo cancellation and noise suppression.
* Added handling for receiving tracks from peers and logging the events.

### Configuration Updates:
* Updated `package.json` to include the `voice-activity-detection` library.
* Modified `vite.config.js` to include `voice-activity-detection` in optimized dependencies.

### Which issue(s) this PR fixes 🔨

- Resolve #821 

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-11-08 22:55 UTC, phillsatellite commented
Hey Lucas! So during testing Sara, Luis and I have found that friending is not working on this pr. Due to this its not possible to test the talking indicator 

We tried old accounts and new accounts, and made sure to do npm i 

User A sends UserB a friend request 
User B accepts request 
User A appears on User B side but User B does not appear on User A side 

We tried moving to different page, refreshing browser and nothing gets User B to appear on User A side

I also tried 2 new accounts before testing this and 2 new accounts before verifying on dev that friending still worked so clean builds before attempting both 

Your branch:

https://github.com/user-attachments/assets/7b3f4103-0874-42ae-916c-6de7e5ce4400

![image](https://github.com/user-attachments/assets/f307825e-4466-4669-840a-71137dda3051)

Dev branch:
![image](https://github.com/user-attachments/assets/f2082736-2698-4b45-88f2-b580f351630a)

2024-11-09 00:15 UTC, stavares843 requested changes
phil added a comment above

2024-11-09 17:42 UTC, luisecm commented
> Hey Lucas! So during testing Sara, Luis and I have found that friending is not working on this pr. Due to this its not possible to test the talking indicator
> 
> We tried old accounts and new accounts, and made sure to do npm i
> 
> User A sends UserB a friend request User B accepts request User A appears on User B side but User B does not appear on User A side
> 
> We tried moving to different page, refreshing browser and nothing gets User B to appear on User A side
> 
> I also tried 2 new accounts before testing this and 2 new accounts before verifying on dev that friending still worked so clean builds before attempting both
> 
> Your branch:
> 
>  Screen_Recording_2024-11-08_at_5.50.39_PM.mov 
> 
> ![image](https://private-user-images.githubusercontent.com/93608357/384545353-f307825e-4466-4669-840a-71137dda3051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzQzNTIsIm5iZiI6MTczMTE3NDA1MiwicGF0aCI6Ii85MzYwODM1Ny8zODQ1NDUzNTMtZjMwNzgyNWUtNDQ2Ni00NjY5LTg0MGEtNzExMzdkZGEzMDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE3NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliNDJlZDcwYzU4YWZkODExZTVlNjUxOGMxNGI0ZGQ5MmRlYTQxZGM3MGM4ZWRjZjcxYzExZDBjYTA0NGFiOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.mPj8gSfn4n2o8h1IIYMZTIbrwoYfkE2ftfwf1jJ3Z9w)
> 
> Dev branch: ![image](https://private-user-images.githubusercontent.com/93608357/384545404-f2082736-2698-4b45-88f2-b580f351630a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNzQzNTIsIm5iZiI6MTczMTE3NDA1MiwicGF0aCI6Ii85MzYwODM1Ny8zODQ1NDU0MDQtZjIwODI3MzYtMjY5OC00YjQ1LTg4ZjItYjU4MGYzNTE2MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA5VDE3NDA1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5ZjhiNzRkYjMxNGNkZGRmY2M5NTE4NjIzOTQyY2NkNGE4ZGQ5MjI3NGZlOWU4MDE2ZjZmZWM5ODk2NTZmYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Acd8ycwaXIW5-yGZ_tG79ixJ8clmcX4FMAtREl1K4tg)

Hello @lgmarchi just wanted to add that the automated tests are failing against this branch for the same reason mentioned above by Phil. I have not seen this error presented in the latest runs of automation tests against dev or any other prs

2024-11-11 18:18 UTC, lgmarchi commented
> Hey Lucas! So during testing Sara, Luis and I have found that friending is not working on this pr. Due to this its not possible to test the talking indicator
> 
> We tried old accounts and new accounts, and made sure to do npm i
> 
> User A sends UserB a friend request User B accepts request User A appears on User B side but User B does not appear on User A side
> 
> We tried moving to different page, refreshing browser and nothing gets User B to appear on User A side
> 
> I also tried 2 new accounts before testing this and 2 new accounts before verifying on dev that friending still worked so clean builds before attempting both
> 
> Your branch:
> 
>  Screen_Recording_2024-11-08_at_5.50.39_PM.mov 
> ![image](https://private-user-images.githubusercontent.com/93608357/384545353-f307825e-4466-4669-840a-71137dda3051.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDgyMTYsIm5iZiI6MTczMTM0NzkxNiwicGF0aCI6Ii85MzYwODM1Ny8zODQ1NDUzNTMtZjMwNzgyNWUtNDQ2Ni00NjY5LTg0MGEtNzExMzdkZGEzMDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE3NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZkYmEwNjFkOTRkNGI1MTc5MDJlOWNkOTdmMGFlNjVhM2IyMThiODBlYjU1ZjVlZDUzYzEzNzUxMDU4NjJhNWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._LaAhAzDezuGcZUiVEmVkmcJrjQQsXrKGRUn8VcNQLo)
> 
> Dev branch: ![image](https://private-user-images.githubusercontent.com/93608357/384545404-f2082736-2698-4b45-88f2-b580f351630a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEzNDgyMTYsIm5iZiI6MTczMTM0NzkxNiwicGF0aCI6Ii85MzYwODM1Ny8zODQ1NDU0MDQtZjIwODI3MzYtMjY5OC00YjQ1LTg4ZjItYjU4MGYzNTE2MzBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTExVDE3NTgzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2YmNhNmYzYjI2ZTY3ZDcxODRkN2NhODI1MDhiY2JkMDlmYjM3NWVjZmNjYTg0MjY4MTk2YmRmOWQ3OTYwNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kI3HxyQpGrNV8jzS6TUOBwTk7RPY6_wWCthXVtGDwU0)

I pushed a commit to solve it.

2024-11-12 00:02 UTC, stavares843 commented on vite.config.js
> +
do we need the empty line here?

2024-11-12 00:02 UTC, stavares843 commented on src/lib/media/Voice.ts
> +    /**
the code comments seems a bit extensive

2024-11-12 00:18 UTC, phillsatellite commented
So the talking indicator is working a lot better but we ran into some other issues when testing (Attempted with new accounts before testing pr, then verified on dev with the same accounts + new ones)

**Issue:**
It seems like after the first call is made and connected, any call after that don't seem to go through. I tried replicating this issue on dev but the dev branch works fine 

**Steps to reproduce:** 
- UserA calls User B - then after call is connected either person hangs up 
- UserB calls back UserA - call does not go through 
- UserA now tries to call UserB again and call does not go through

**Logs:**
UserA
<img width="849" alt="UserA" src="https://github.com/user-attachments/assets/db2f8bf4-47a5-483a-8db1-27efec2f4931">

UserB
<img width="847" alt="UserB" src="https://github.com/user-attachments/assets/e302b1c3-1ab6-458f-9c9c-100f9d7a08c6">

**Screen recordings:**
This branch 

https://github.com/user-attachments/assets/e5b4a8af-f82d-4f50-bf7d-8b4bdd6444e9

Dev branch

https://github.com/user-attachments/assets/83f12535-9bb4-4a55-a01b-d155034e2ec3

2024-11-12 01:29 UTC, luisecm commented
I see that friend requests are working again within latest commit

2024-11-13 11:50 UTC, lgmarchi commented
> So the talking indicator is working a lot better but we ran into some other issues when testing (Attempted with new accounts before testing pr, then verified on dev with the same accounts + new ones)
> 
> **Issue:** It seems like after the first call is made and connected, any call after that don't seem to go through. I tried replicating this issue on dev but the dev branch works fine
> 
> **Steps to reproduce:**
> 
> * UserA calls User B - then after call is connected either person hangs up
> * UserB calls back UserA - call does not go through
> * UserA now tries to call UserB again and call does not go through
> 
> **Logs:** UserA <img alt="UserA" width="849" src="https://private-user-images.githubusercontent.com/93608357/385093603-db2f8bf4-47a5-483a-8db1-27efec2f4931.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTgxMjMsIm5iZiI6MTczMTQ5NzgyMywicGF0aCI6Ii85MzYwODM1Ny8zODUwOTM2MDMtZGIyZjhiZjQtNDdhNS00ODNhLThkYjEtMjdlZmVjMmY0OTMxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYjExZWNhZWE4MGFmMDFlYzI5ZDRhNjNhMzY3MGQwNjg4YWYxNjRiODFmMWU5OGViOWJhNjUwYTE4OGI1ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.NfgY6JqYgUoFb8Z5mb-g3x1Y_nCdbPDvfWNfIBSR_uc">
> 
> UserB <img alt="UserB" width="847" src="https://private-user-images.githubusercontent.com/93608357/385093622-e302b1c3-1ab6-458f-9c9c-100f9d7a08c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE0OTgxMjMsIm5iZiI6MTczMTQ5NzgyMywicGF0aCI6Ii85MzYwODM1Ny8zODUwOTM2MjItZTMwMmIxYzMtMWFiNi00NThmLTljOWMtMTAwZjlkN2EwOGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDExMzcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4ZGY2ZmFiYjljOWI5MTk3MjA3MGQyMmJmZGRlYzhiZjMxMzNmYzAzNjExMDVjYjBhZGNhNWM2ODRhZWU5OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VH-s4xwXT76tUEVoA_yeZoWAlu-mmDZIwXJPEXs66fY">
> 
> **Screen recordings:** This branch
> 
>  Branch.mov 
> Dev branch
> 
>  DevBranch.mov

I pushed a commit that should solve that.

2024-11-13 17:42 UTC, stavares843 reviewed
so like @phillsatellite and i tested and i was talking to phil audio was pretty high but on my user there was zero indicator on my user

![image](https://github.com/user-attachments/assets/09b00362-f3ae-4acf-89e5-6fc1679df335)


there was on phil side though and on phil side when he spoke he mentioned he had a talking indicator on his user

2024-11-13 17:45 UTC, lgmarchi commented
> so like @phillsatellite and i tested and i was talking to phil audio was pretty high but on my user there was zero indicator on my user
> 
> ![image](https://private-user-images.githubusercontent.com/29093946/385877679-09b00362-f3ae-4acf-89e5-6fc1679df335.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE1MjAxMDcsIm5iZiI6MTczMTUxOTgwNywicGF0aCI6Ii8yOTA5Mzk0Ni8zODU4Nzc2NzktMDliMDAzNjItZjNhZS00YWNmLTg5ZTUtNmZjMTY3OWRmMzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTEzVDE3NDMyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOTgxNTBkYTU0OTM3M2RhZjlmYjljYWYzNmE3OWRhYWIxNWMzMWY5N2M0ZTFjNDllNTM1YmQ3OTcwNGIxMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bPlMRqBjxU4Iqq_X76x3xDCM9dOM6CZ1jXR8oY0nEdw)
> 
> there was on phil side though and on phil side when he spoke he mentioned he had a talking indicator on his user

So the problem is, when you are talking, no indicator appears to you for your user?

2024-11-13 17:52 UTC, stavares843 commented
that is correct

2024-11-13 17:58 UTC, lgmarchi commented
> that is correct

Which browser? And is it private?

2024-11-13 18:45 UTC, stavares843 commented
chrome, macOS

private browser yes

2024-11-13 19:20 UTC, lgmarchi commented
> chrome, macOS
> 
> private browser yes

Try on normal browser, I am not sure on private it should works nice.

I did 3 tests now with @tooshel , worked all of them, including private browser too.

More thoughts about it? Want to test with other users?

2024-11-14 01:00 UTC, stavares843 approved these changes

2024-11-14 01:00 UTC, phillsatellite approved these changes

2024-11-14 01:00 UTC, stavares843 commented
we approved for now, maybe we can improve in the future

2024-11-14 12:33 UTC, ashneverdawn approved these changes

2024-11-14 12:45 UTC, merged