feat(mobile): add device detection and screen orientation locking to portrait
Satellite-im/UplinkWeb pull request #896
Opened 2024-11-28 20:18 UTC by lgmarchi

### What this PR does 📖

> [!IMPORTANT]
> Screen orientation lock was added, because app is not working really good yet in landscape orientation 

This pull request includes changes to add mobile device detection and screen orientation locking functionality. The main changes involve importing new dependencies, adding a utility function to detect mobile platforms, and locking the screen orientation for specific devices.

### Mobile device detection and screen orientation locking:

* [`src/lib/utils/Mobile.ts`](diffhunk://#diff-8ff4a5d9edf728fc9c713852815e46bc99e4cc51dcc799a244c8d11abf275828R1-R10): Added a new function `isAndroidOriOS` to detect if the device is running on Android or iOS.
* [`src/routes/+layout.svelte`](diffhunk://#diff-cc69d6a97e4f62578028d872b8d5032f2786fe1eaa65735429286b375234168dR30-R31): Imported `ScreenOrientation` and `isAndroidOriOS` to handle screen orientation locking.
* [`src/routes/+layout.svelte`](diffhunk://#diff-cc69d6a97e4f62578028d872b8d5032f2786fe1eaa65735429286b375234168dR269-R281): Added the `lockOrientation` function to lock the screen orientation to portrait mode and integrated it with the `onMount` lifecycle method to execute on supported devices.

### Which issue(s) this PR fixes 🔨

-   Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-11-28 22:15 UTC, stavares843 commented on ios/App/Podfile.lock
> +COCOAPODS: 1.15.2
this is being downgraded, i believe you need to update your pods locally

2024-11-28 22:28 UTC, stavares843 reviewed
@lgmarchi we don't need any of that to force the orientations 


just this updating from

<img width="616" alt="Captura de ecrã 2024-11-28, às 22 10 47" src="https://github.com/user-attachments/assets/4b1ce859-bc91-4260-9207-f7cd4b5d43e1">




to this

<img width="573" alt="Captura de ecrã 2024-11-28, às 22 27 35" src="https://github.com/user-attachments/assets/83f4eb0b-401e-458f-a3b4-bee4117c3935">

and will force the portrait even if you are on landscape

<img width="804" alt="Captura de ecrã 2024-11-28, às 22 28 09" src="https://github.com/user-attachments/assets/3382b4d6-5c13-48bb-9501-1776a3b07a9b">

2024-11-28 22:30 UTC, stavares843 requested changes
added comments above

2024-11-28 22:32 UTC, stavares843 commented
i mean if you want we can add those plugins and the utility function you added regardless @lgmarchi 

was just explaining that it was not needed to achieve what you mentioned in this case, to block the landscape orientation

2024-11-28 22:39 UTC, lgmarchi commented
> @lgmarchi we don't need any of that to force the orientations
> 
> just this updating from
> 

This code can work for Android devices as well. And it is easier to just remove when need to give maintenance on it,

> i mean if you want we can add those plugins and the utility function you added regardless @lgmarchi
> 
> was just explaining that it was not needed to achieve what you mentioned in this case, to block the landscape orientation

Both approaches work, but I chose this method because it keeps the code consistent across iOS and Android, making it easier to manage. It allows dynamic control of orientation—like locking portrait for most pages but enabling landscape for specific ones when needed. It’s also simpler to update or remove during testing compared to editing platform-specific files like `Info.plist` or `AndroidManifest.xml`.

2024-11-28 22:48 UTC, stavares843 commented
Again, not against merging the PR with the plugins and the utility function though.

>  It allows dynamic control of orientation—like locking portrait for most pages but enabling landscape for specific ones when needed.

but seems we aren't using that on the PR - can you add a example for when we use that in the future then?

Can you update the pods? They are downgrading on this PR.

2024-11-29 03:24 UTC, luisecm commented
Minor comment, we should use our logger instead of console.error

2024-11-29 17:51 UTC, lgmarchi commented
> Member

One example will be when we have landscape videos or images, and users want to see them in landscape orientation. 

Other example could be during group calls, maybe user prefer to see in landscape orientation as well. 

Storage section for example is a screen very good to be possible use in landscape orientation as well, while user can see files, can see files tree as well.

2024-11-29 18:23 UTC, stavares843 commented
Yes I get that I meant a example in code

2024-11-29 18:34 UTC, stavares843 commented
also, if I wanted to speak with AI I would go to chatgpt

2024-12-02 14:44 UTC, lgmarchi commented
> Yes I get that I meant a example in code

You asked for a future example—`could you kindly provide an example of when we might use that in the future?` I've provided my answer to clarify.

2024-12-02 15:45 UTC, stavares843 commented
no i did not said that lol

i said

> can you add a example for when we use that in the future then?


i mean in code - not in theory obviously

if you are adding this code, we could also add the theory of what pages to hide right? then anyone knows how to add/delete one in the future

2024-12-02 17:59 UTC, luisecm commented
@lgmarchi Hello Lucas, I see the same issue again on this branch - Install Banner is not shown on web. Could you please address this bug? Seems like every time we touch files for some strange reason the install banner is being affected


https://github.com/user-attachments/assets/0f10e511-36ef-4a8c-a3c8-3491d77ce846

2024-12-02 18:44 UTC, stavares843 requested changes
luis comment needs fixing

2024-12-02 21:27 UTC, stavares843 commented
we will retest with the latest PR that was merged regarding luis comment

2024-12-04 16:52 UTC, phillsatellite commented
Hey @lgmarchi so during testing I was able to turn the device horizontally and rest of the app changed orientation as well. The goal of this pr is to block this correct? 

<img width="1050" alt="Screenshot 2024-12-04 at 11 50 44 AM" src="https://github.com/user-attachments/assets/995c2768-6910-438b-8126-a27cdaa0e8f4">

2024-12-04 17:42 UTC, lgmarchi commented
> Hey @lgmarchi so during testing I was able to turn the device horizontally and rest of the app changed orientation as well. The goal of this pr is to block this correct?
> 
> <img alt="Screenshot 2024-12-04 at 11 50 44 AM" width="1050" src="https://private-user-images.githubusercontent.com/93608357/392488684-995c2768-6910-438b-8126-a27cdaa0e8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzQzNzMsIm5iZiI6MTczMzMzNDA3MywicGF0aCI6Ii85MzYwODM1Ny8zOTI0ODg2ODQtOTk1YzI3NjgtNjkxMC00MzhiLTgxMjYtYTI3Y2RhYTBlOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTc0YjRhODNkMjhkYTBkMzYyMGM5OGIzOWVmN2I1MzNjY2E3NWJiMGExNzdkN2NhMTI4ZjhlMWFmMjRiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fkGRF2kY4EWvtbusMhZkLBYdHDBciIPjPX3YJnbH_kE">

Yes, it should not happen. 

Did you do npm install before? Because there is a new lib that need to be used. And you can not change branch and test. 

You need to change branch, and run code to run app again from beginning.

2024-12-04 19:55 UTC, phillsatellite commented
> > Hey @lgmarchi so during testing I was able to turn the device horizontally and rest of the app changed orientation as well. The goal of this pr is to block this correct?
> > <img alt="Screenshot 2024-12-04 at 11 50 44 AM" width="1050" src="https://private-user-images.githubusercontent.com/93608357/392488684-995c2768-6910-438b-8126-a27cdaa0e8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzQzNzMsIm5iZiI6MTczMzMzNDA3MywicGF0aCI6Ii85MzYwODM1Ny8zOTI0ODg2ODQtOTk1YzI3NjgtNjkxMC00MzhiLTgxMjYtYTI3Y2RhYTBlOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTc0YjRhODNkMjhkYTBkMzYyMGM5OGIzOWVmN2I1MzNjY2E3NWJiMGExNzdkN2NhMTI4ZjhlMWFmMjRiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fkGRF2kY4EWvtbusMhZkLBYdHDBciIPjPX3YJnbH_kE">
> 
> Yes, it should not happen.
> 
> Did you do npm install before? Because there is a new lib that need to be used. And you can not change branch and test.
> 
> You need to change branch, and run code to run app again from beginning.

Did do all of these steps. Sara had tried a first time and it worked but now her second time trying it isnt working. Could be from when the conflicts got fixed?

2024-12-04 22:18 UTC, lgmarchi commented
> > > Hey @lgmarchi so during testing I was able to turn the device horizontally and rest of the app changed orientation as well. The goal of this pr is to block this correct?
> > > <img alt="Screenshot 2024-12-04 at 11 50 44 AM" width="1050" src="https://private-user-images.githubusercontent.com/93608357/392488684-995c2768-6910-438b-8126-a27cdaa0e8f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMzMzQzNzMsIm5iZiI6MTczMzMzNDA3MywicGF0aCI6Ii85MzYwODM1Ny8zOTI0ODg2ODQtOTk1YzI3NjgtNjkxMC00MzhiLTgxMjYtYTI3Y2RhYTBlOGY0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjA0VDE3NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzOTc0YjRhODNkMjhkYTBkMzYyMGM5OGIzOWVmN2I1MzNjY2E3NWJiMGExNzdkN2NhMTI4ZjhlMWFmMjRiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fkGRF2kY4EWvtbusMhZkLBYdHDBciIPjPX3YJnbH_kE">
> > 
> > 
> > Yes, it should not happen.
> > Did you do npm install before? Because there is a new lib that need to be used. And you can not change branch and test.
> > You need to change branch, and run code to run app again from beginning.
> 
> Did do all of these steps. Sara had tried a first time and it worked but now her second time trying it isnt working. Could be from when the conflicts got fixed?

Yes, it was. I saw code, conflict mix some code.

2024-12-04 23:35 UTC, stavares843 approved these changes

2024-12-04 23:36 UTC, phillsatellite approved these changes

2024-12-04 23:36 UTC, merged