fix(Mobile): Fix copy did on friends page in mobile
Satellite-im/UplinkWeb pull request #897
Opened 2024-11-28 21:04 UTC by lgmarchi

### What this PR does 📖

- With old code, copy DID was not working properly on mobile, so now is guaranteed DID string is on clipboard

### Which issue(s) this PR fixes 🔨

-   Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-12-02 18:43 UTC, stavares843 requested changes

2024-12-02 18:43 UTC, stavares843 commented on ios/App/Podfile.lock
> +COCOAPODS: 1.15.2
this is downgrading

2024-12-03 22:54 UTC, phillsatellite approved these changes

2024-12-03 22:55 UTC, phillsatellite commented
Never experienced this bug on dev/mobile but still works great when testing so approved! 🍏

2024-12-03 23:07 UTC, stavares843 approved these changes

2024-12-03 23:07 UTC, merged