fix(Mobile): Add a correct check to show or not keybinds section
Satellite-im/UplinkWeb pull request #899
Opened 2024-11-29 13:18 UTC by lgmarchi

### What this PR does 📖

- Old code was using width to check if it is mobile or not, but even on web, if user is using with small width, it should keep showing keybinds section, so this PR fix that, and hide this section just in mobile.

### Which issue(s) this PR fixes 🔨

-   Resolve #

### Special notes for reviewers 🗒️

### Additional comments 🎤

2024-12-02 17:53 UTC, luisecm commented
@lgmarchi Hello Lucas, I noticed that also in this PR the install banner is not shown on web, and this is why automated tests are failing. I noticed that when we mess with the OnMount method we can alter the behavior of the banner. Could you please fix this?

![image](https://github.com/user-attachments/assets/a4b2675f-1e61-4e4b-862a-ed15cdc8ba27)

2024-12-02 18:42 UTC, stavares843 requested changes
luis comment needs fixing

2024-12-02 21:27 UTC, stavares843 commented
we will retest with the latest PR that was merged

2024-12-04 00:00 UTC, phillsatellite approved these changes

2024-12-04 00:04 UTC, stavares843 approved these changes

2024-12-04 00:05 UTC, merged